awslabs/sbt-aws

.github/workflows/build.yml, .github/workflows/upgrade-main.yml, .projenrc.ts
Some of the projen workflows require repo access for mutation. I think this can be accomplished with the GITHUB_TOKEN vs. the PROJEN_GITHUB_TOKEN.
---
=> chore: update secret name

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/notice.yml, .github/pull_request_template.md, .github/workflows/pull-request-lint.yml, .projenrc.ts
Added issue templates. Copied, mostly, from aws-cdk.
---
=> chore: add issue templates

README.md
Fixes the roadmap navigation link inside of the readme to properly point to the roadmap of the SBT readme rather than the CDK. 
---
=> docs: Readme navigation fix for roadmap link

src/control-plane/control-plane.ts, src/core-app-plane/core-app-plane.ts, src/utils/index.ts, src/utils/utils.ts, test/control-plane.test.ts
Adds internal telemetry for CloudFormation
* Added a function that will set the template description, and called the function from both ControlPlane and CoreApplicationPlane
Added unit tests. Util function has 100% coverage.
---
=> feat: Add CloudFormation telemetry

docs/public/README.md
Fixes the test for onboarding new tenants from the command line.
- No longer sends Tenant ID when creating a Tenant
- Now just tests creation by getting all tenants (vs. tenant with ID)
Closes #16
No code changes, only docs.
---
=> docs: Fixes #16 - Documentation issue for testing deployment

resources/functions/tenant-management/index.py, scripts/test-sbt-aws.sh
Closes #8 
Check if tenant id exists before updating the tenant.
---
=> fix: check existence of tenant before updating

API.md, docs/public/README.md, src/control-plane/control-plane-api.ts, src/control-plane/control-plane.ts, test/control-plane.test.ts
Now explicitly creates the IAM Role allowing APIGW to publish to CloudWatch. Customers can opt out by passing the `disableAPILogging` property to the ControlPlane props
Closes #19
Deployment into a fresh account fails without this change. Now creates the rest API construct with a flag to explicitly create the IAM Role that allows API GW to push to CloudWatch.
Added a new field to the `ControlPlaneProps` called `disableAPILogging`. It's optional with a default of false. Also modified docs to surface this change.
Wrote unit tests to validate the synthed template with and without the flag.
---
=> fix: Fix for 19

.github/workflows/release_cdklabs-sbt-point-solutions-lib.yml, .projenrc.ts
The auto generated sub project release github action is not installing dependencies from sub project.
Updated the sub project release github action, by adding a job to install dependencies from sub project.
Generated sub project release github action now uses sub project folder location
---
=> fix: Point solutions release github action 

src/control-plane/auth/cognito-auth.ts, src/control-plane/billing/billing-provider.ts, src/control-plane/control-plane-api.ts, src/control-plane/control-plane.ts, src/control-plane/ingestor-aggregator/firehose-ingestor-aggregator.ts, src/control-plane/services.ts, src/control-plane/tables.ts, src/control-plane/tenant-config/tenant-config-service.ts, src/core-app-plane/bash-job-orchestrator.ts, src/core-app-plane/bash-job-runner.ts, src/core-app-plane/core-app-plane.ts, src/utils/event-manager.ts, src/utils/utils.ts, test/control-plane.test.ts, test/utils.test.ts
=> feat: updated telemetry with tags

.projen/tasks.json, .projenrc.ts, src/point-solutions/libraries/.projen/tasks.json
Since there is only one tag the github actions are publishing to any one npm org
Added different release tags for sbt components and point solutions 
github actions will create different release tags for sbt components and point solutions 
---
=> fix: Added different release tags for sbt components and point solutions

API.md, src/control-plane/billing/billing-provider.ts, src/control-plane/control-plane.ts, src/core-app-plane/core-app-plane.ts, src/utils/event-manager.ts, test/core-app-plane.test.ts, test/event-manager.test.ts
This fixes a bug where the `addTargetToEvent(...)` function was causing the EventManager stack to be dependent on stacks that used that function.
Instead of creating the rule in the EventManager stack, this change now creates the rule in the calling stack.
Added lots of tests!
---
=> fix: event manager cyclic dep

src/control-plane/auth/cognito-auth.ts, src/control-plane/control-plane.ts, src/control-plane/integ.default.ts, src/utils/event-manager.ts, test/event-manager.test.ts
The change is to fix an issue with the `EventManager` class and ensure that all `DetailType` enum entries have corresponding values in the `supportedEvents` object. This is necessary to prevent errors when creating new event-manager rules using the `getOrCreateRule` function.
Marking this as a breaking change because the default CognitoAuth no longer disables setting of scopes for API GWs.
1. In `src/utils/event-manager.ts`, the `supportedEvents` object is updated to include entries for `tenantUserCreated` and `tenantUserDeleted` events.
2. A new test suite is added in `test/event-manager.test.ts` to ensure that all `DetailType` enum entries have corresponding values in the `supportedEvents` object.
3. In `src/control-plane/integ.default.ts`, a `CognitoAuth` …
=> fix!: Bugfix/supported events missing key

API.md, scripts/sbt-aws.sh, src/control-plane/auth/cognito-auth.ts, src/control-plane/control-plane-api.ts, src/control-plane/control-plane.ts
We should be able to set the CORS config for the control plane API. I am running into an issue when running the serverless ref arch and accessing the API (on a different domain) via the UI hosted on cloudfront.
- Added (optional) parameters that can be passed into the control plane to set the cors config for the control plane API.
- Update Cognito UserPool domain name prefix so that it includes username.
---
=> fix: add cors parameter and rename duplicate construct id names

resources/functions/user-management/cognito_user_management_service.py
Closes #70 
Stringifying the dict led to a stringified json object
No longer stringifying the dict.
Tested with serverless-ref-arch
---
=> fix: avoid stringifying json response

src/control-plane/aws-marketplace/saas-product.ts
A key name of the environment variable for market place seller email is wrong on RegisterNewMarketplaceCustomerPython Lambda function.
It causes that lambda function never send an email to buyers.
fix key name
---
=> fix: lambda env key name fix

.projen/deps.json, .projenrc.ts, API.md, docs/public/README.md, package-lock.json, package.json, scripts/sbt-aws.sh, src/control-plane/integ.default.ts, src/control-plane/tenant-management/tenant-management.service.ts, src/core-app-plane/core-app-plane.ts, src/core-app-plane/index.ts, src/core-app-plane/integ.default.ts, src/core-app-plane/script-job.ts, src/core-app-plane/tenant-lifecycle-script-jobs.ts, test/core-app-plane.test.ts, test/event-manager.test.ts
Closes #73 
#73 
This commit refactors the BashJobRunner construct into a more generic ScriptJob construct. It also introduces two new constructs, ProvisioningScriptJob and DeprovisioningScriptJob, which are wrappers around ScriptJob with predefined configurations for tenant provisioning and deprovisioning scenarios.
The main changes include:
- Rename BashJobRunner to ScriptJob and update related interfaces and properties
- Add OutgoingEventDetailTypes interface to represent success and failure detail types
- Introduce ProvisioningScriptJob and DeprovisioningScriptJob constructs
- Update CoreApplicationPlane to use scriptJobs instead of jobRunnersList
- Update integration tests and documentation accordingly
This refactoring provides a more flexible and extensible approach for running …
=> refactor(core-app-plane)!: replace BashJobRunner with ScriptJob

src/control-plane/metering/metering-interface.ts
Add metering interface in control plane.
This pull request introduces a new interface for Metering, a new component in the control plane. The Metering interface aims to provide a standardized way of measuring and tracking resource usage at tenant level across the platform.
- Define an IMetering interface with the following methods
- createMeterFunction
- updateMeterFunction
- ingestFunction
- getUsageFunction
- cancelUsageEventsFunction
- createCustomerFunction
- deleteCustomerFunction
By defining a standardized Metering interface, we can enable multiple metering providers to implement their own plugins. This interface provides a clear contract for metering functionality, allowing for seamless integration with the control plane components. 
- Integrate …
=> feat: add interface for metering component

API.md, src/control-plane/billing/billing-interface.ts, src/control-plane/billing/billing-provider.ts, src/control-plane/control-plane.ts, src/control-plane/index.ts, src/control-plane/metering/index.ts, src/control-plane/metering/metering-interface.ts, src/control-plane/metering/metering-provider.ts, src/utils/event-manager.ts, src/utils/utils.ts
The primary reason for these changes is to introduce a new construct called `MeteringProvider` that handles metering-related operations and integrates with the control plane.
1. **`MeteringProvider` construct**: I created a new construct called `MeteringProvider` that encapsulates the metering-related functionality. This construct takes an implementation of the `IMetering` interface as a prop and sets up the necessary event targets and API routes for metering operations. Specifically, it:
- Attaches functions to handle events like `ONBOARDING_REQUEST`, `OFFBOARDING_REQUEST`, and `INGEST_USAGE`.
- Adds API routes for creating meters (`POST /meters`), updating meters (`PUT /meters/{meterId}`), fetching usage data (`GET /usage/{meterId}`), and canceling usage …
=> feat: connect metering concrete implementation to control plane

API.md, src/control-plane/metering/index.ts, src/control-plane/metering/metering-provider.ts
I incorrectly configured the API path for updating meters (PUT /meters/{meterId})
---
=> fix: export and add docs for metering-provider and fix update meters endpoint

src/control-plane/auth/cognito-auth.ts, src/control-plane/aws-marketplace/sample-registration-web-page.ts, test/control-plane.test.ts
Closes #84 
Fix NagSuppression issue when using SBT in pipeline stage.
Use `findChild()` function to get the proper path of the resource instead of hardcoding it based on resource ID.
Replicated the template outlined in #84 and made sure the error was resolved.
---
=> fix: use proper pathing for nagsuppression of cdk-managed resources

.projenrc.ts, API.md, resources/functions/tenant-management/index.py, resources/functions/tenant-registrations/index.py, resources/layers/helper/requirements.txt, scripts/sbt-aws.sh, scripts/test-sbt-aws.sh, src/control-plane/auth/auth-interface.ts, src/control-plane/control-plane.ts, src/control-plane/index.ts, src/control-plane/tenant-config/tenant-config-funcs.ts, src/control-plane/tenant-management/tenant-management-funcs.ts, src/control-plane/tenant-management/tenant-management.service.ts, src/control-plane/tenant-registration/index.ts, src/control-plane/tenant-registration/tenant-registration-funcs.ts, src/control-plane/tenant-registration/tenant-registration.service.ts, src/control-plane/tenant-registration/tenant-registration.table.ts, src/core-app-plane/integ.default.ts, src/core-app-plane/script-job.ts, src/core-app-plane/tenant-lifecycle-script-jobs.ts, src/utils/utils.ts
=> feat: add tenant-registration service

src/control-plane/ingestor-aggregator/firehose-ingestor-aggregator.ts
This fixes the error that occurs when auto deleting firehose destination bucket. The fix was to set the removal policy to destroy the bucket.
---
=> fix: set removal policy when auto deleting firehose bucket objects

src/control-plane/billing/mock-billing-provider.ts
- Output table names for BillingTable, CustomersTable, and IngestorTable
- Output function name for PutUsage Lambda function
---
=> fix: add CDK outputs for mock billing related resources

CONTRIBUTING.md
Seems like https://projen.io/releases.html is no longer valid, so changing to the landing site 
Minor fix in the docs
Followed the link
---
=> docs: Fixing broken link to projen.io

API.md, docs/public/README.md, src/control-plane/auth/cognito-auth.ts, src/control-plane/integ.default.ts, website/docs/tutorials/tutorial-basics/create-control-plane.md
Closes #141.
For testing purposes, this feature allows it not generate additional costs from Cognito.
I created a new parameter `enableAdvancedSecurityMode` in the CognitoAuthProps interface to define whether the advancedSecurityMode attribute of the Cognito User Pool will be enabled or not. This parameter is optional and its default value is true.
I ran these commands and the tests passed successfully:
`npm install`
`npm run build`
---
=> feat: Added support to configure advancedSecurityMode on ControlPlane

docs/public/README.md, resources/functions/tenant-registrations/index.py
- Tenant management table lacks tenantRegistrationId
- SaaS provider UI (Admin) should display tenant information
- Tenant removal API call from UI is hindered without tenantRegistrationId
The create_tenant_registration of Tenant Registration Lambda.
- Add tenantRegistrationId value to tenant_data dictionary
- Removed tenantRegistrationId from __create_control_plane_event
- Tenant Removal test from UI.
---
=> feat: Adding a tenantRegistrationId column to tenantManagementTable

CONTRIBUTING.md
…e ARN to connect the two planes
CONTRIBUTING.md does not instruct users to use the Eventbridge ARN from the control plane when deploying the core app plane, resulting in the deployment of the two planes without any communication. This will also result in the failure of the test scripts when provisioning and deprovisioning tenants, as there is no prior instruction to connect the two planes when deploying. 
Edited CONTRIBUTING.md 
N/A
---
=> fix: updated contributing instructions

src/core-app-plane/script-job.ts
Closes #120 120.
This is a feature request for CodeBuild created by SBT AppPlane to support cloning private Git repos.
I have added a field [here] (https://github.com/awslabs/sbt-aws/blob/137b1fcb73ec7d56d01f959a03a02300eff600e3/src/core-app-plane/script-job.ts#L241)
The field I have added is to enable [git-credential-helper] (https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec.env.git-credential-helper)
I updated node modules locally and added the same field in the file 'bash-job-runner.js'
```
buildSpec: codebuild.BuildSpec.fromObject({
version: '0.2',
env: {
'git-credential-helper': 'yes',
shell: 'bash',
...(props.environmentVariablesToOutgoingEvent && {
'exported-variables': props.environmentVariablesToOutgoingEvent,
}),
},
phases: {
build: { …
```
=> feat: Added support for Git credential helper

.github/workflows/run-tests.yml, projenrc/run-tests-workflow.ts
This change adds the workflow_dispatch event trigger to the run-tests GitHub Actions workflow, allowing repository administrators to manually trigger the workflow from the GitHub UI. This is particularly useful for testing workflows that require access to repository secrets, which are not available when workflows are triggered from fork pull requests.
---
=> feat: add workflow_dispatch trigger to run-tests workflow

.github/workflows/run-tests.yml, projenrc/run-tests-workflow.ts
=> fix: Make run-tests job always depend on build job

API.md, src/core-app-plane/integ.default.ts, src/core-app-plane/script-job.ts, src/core-app-plane/tenant-lifecycle-script-jobs.ts
ScriptJob (and by extension ProvisioningScriptJob and DeProvisioningScriptJob) don't have a way to modify the CodeBuild project properties. For example, one may wish to use Lambda ARM compute resources, or optimise for build performance.
Added CodeBuild ProjectProps as a optional input for ScriptJobProps and TenantLifecycleScriptJobProps. These will overwrite defaults so discretion is advised. In general, if you're playing in here then you should understand what you're doing. I feel the flexibility is justified.
Added extra properties to the integration test for the core app. It deploys with Lambda ARM which is non-default.
---
*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the …
=> feat: Extend ScriptJob CodeBuild Project props
