- .github/workflows/pull-request-lint.yml
- .projenrc.ts
Updates the allowed semantic titles for PRs. Happy to hear feedback on whether or not all of these should be in here.
---
> fix: Update accepted semantic titles for PRs

- README.md
Updated construct hub badge
Added badges for release and NPM
---
> chore: Update docs/badges

- API.md
- docs/public/README.md
- resources/functions/tenant-management/index.py
- src/control-plane/auth/auth-interface.ts
- src/control-plane/auth/cognito-auth.ts
- src/control-plane/billing/billing-interface.ts
- src/control-plane/billing/billing-provider.ts
- src/utils/event-manager.ts
…perations
The billing interface also needs to support the ability to trigger functions based on user lifecycle events.
- Add `createCustomerFunction` and `deleteCustomerFunction` properties
to the `IBilling` interface, representing functions to create and
delete customers (entities with zero or more users).
- Add optional `createUserFunction` and `deleteUserFunction` properties
to the `IBilling` interface, representing functions to create and
delete users belonging to a customer.
- Add `IFunctionTrigger` and `IFunctionSchedule` interfaces to support
triggering functions based on events or schedules, respectively.
- Update the `BillingProvider` construct to create event targets for the
new customer and user management functions, and to optionally create a …
> feat(billing): add support for customer and user management

- docs/public/README.kr.md
Add a Korean README for Korea customers and partners
Korean version README.kr.md file add
- Test Script part fixed.(only  README.kr.md)
- Translated README.md into Korean
Self Reviewed.
- Create Control Plane / Application Plane as Korean guided.
- Test with a fixed script
---
> docs: Add Korean readme

- docs/public/README.md
Updates the test steps in the user guide to test the deployment.
---
> docs: fix steps in guide

- README.md
Added feature request/feedback link to README.md
---
> docs: Added feedback link to docs

- README.md
> docs: update link for serverless ref arch example

- .projen/tasks.json
- .projenrc.ts
- src/point-solutions/libraries/.projen/tasks.json
Version has been changed to 0.0.0
updated the tag names to reflect latest version
The released tags will have updated tag names
- [ x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/awslabs/sbt-aws/blob/main/CONTRIBUTING.md)
---
> fix: npm release fix

- docs/public/README.md
> docs: add version to sbt-aws install instruction in public/README.md

- src/utils/utils.ts
- test/utils.test.ts
Tag name is incorrect.
Changed telemetry tag from Tags to tag
Updated tests as appropriate.
---
> fix: updated tag name

- .projen/deps.json
- .projen/tasks.json
- .projenrc.ts
- package-lock.json
- package.json
Closes https://github.com/awslabs/sbt-aws/security/dependabot/1
---
> fix: add fix for CVE-2024-4068

- API.md
- src/control-plane/auth/cognito-auth.ts
- src/core-app-plane/integ.default.ts
Nightly build is failing
Added new resource path structure
- [ x] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/awslabs/sbt-aws/blob/main/CONTRIBUTING.md)
- [ x] I have updated the relevant documentation (if applicable).
---
> fix: Job runner test fix

- docs/public/README.md
controplane export IEvnetManager not EventManager
---
> fix: ReadMe sample fix

- website/package-lock.json
Fixes the website build.
Updated the package-lock.json with a fresh npm install
---
> fix: recommitting package-lock

- API.md
- src/core-app-plane/script-job.ts
- src/core-app-plane/tenant-lifecycle-script-jobs.ts
Allows users to provide a CodeBuild.Source to ScriptJobs
---
> feat: add source parameter to ScriptJobs

- API.md
- resources/functions/tenant-registrations/index.py
- scripts/sbt-aws.sh
- scripts/test-sbt-aws.sh
- src/control-plane/tenant-registration/tenant-registration.service.ts
- Update API documentation and class names for clarity
- Implement pagination for listing tenant registrations
- Add input validation and improve error responses
- Update test scripts to cover new functionality
- Refactor lambda function for better error handling and response formatting
---
> feat: Enhance tenant registration service and improve error handling

- API.md
- docs/public/README.md
- resources/functions/mock-billing/create-customer/index.py
- resources/functions/mock-billing/delete-customer/index.py
- resources/functions/mock-billing/put-usage/index.py
- scripts/send-kinesis-data.sh
- src/control-plane/aws-marketplace/entitlement-logic.ts
- src/control-plane/aws-marketplace/saas-product.ts
- src/control-plane/billing/index.ts
- src/control-plane/billing/mock-billing-provider.ts
- src/control-plane/ingestor-aggregator/firehose-ingestor-aggregator.ts
- src/control-plane/integ.default.ts
- Implement MockBillingProvider class with create/delete customer functions
- Add FirehoseAggregator for billing data ingestion
- Create DynamoDB tables for billing and customer records
- Add Python Lambda functions for billing operations
- Update FirehoseAggregator with autoDeleteObjects option
- Integrate MockBillingProvider in ControlPlane
---
> feat: Add MockBillingProvider and related components

- docs/public/README.md
Update sample code to follow the correct types.
No issue
The test code will not build because of changes in the core library
- Get eventManager from props
- Add tenantData[] to environmentVariablesToOutgoingEvent
The example code will not run without these changes.
---
> docs: Correct example code in developer guide README.md

- docs/public/README.md
No issue
The test code will not build because of changes in the core library
Get eventManager from props
Add tenantData[] to environmentVariablesToOutgoingEvent
The example code will not run without these changes.
---
> docs: Update Developer Guide example code

- README.md
> docs: add public roadmap link to readme

- src/control-plane/auth/cognito-auth.ts
- test/cognito-auth.test.ts
> fix: advanced security mode

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/run-tests.yml
- .projenrc.ts
- projenrc/run-tests-workflow.ts
- src/control-plane/auth/cognito-auth.ts
- src/control-plane/aws-marketplace/saas-product.ts
- src/control-plane/billing/mock-billing-provider.ts
- src/control-plane/ingestor-aggregator/firehose-ingestor-aggregator.ts
- src/control-plane/tenant-config/tenant-config-funcs.ts
- src/control-plane/tenant-management/tenant-management-funcs.ts
- src/control-plane/tenant-registration/tenant-registration-funcs.ts
- Update Lambda layer ARNs from x86_64 to arm64 across all services
- Add Architecture import from aws-cdk-lib/aws-lambda in affected files
---
> refactor!: Migrate Lambda functions to ARM64 architecture

- .github/workflows/run-tests.yml
- .mise.toml
- .projenrc.ts
- projenrc/run-tests-workflow.ts
> feat: update run tests workflow

- .github/workflows/run-tests.yml
- .projenrc.ts
- projenrc/run-tests-workflow.ts
> fix: remove deps for run-tests job

- scripts/github-actions-run-tests-script.sh
- scripts/test-sbt-aws.sh
- include git branch name when testing
- increase waiting period when testing for changes
---
> fix: update github action script
